### ISSUE TITLE
Single or Single-End

### ISSUE THREAD

**Issue by HLWeil** [nfdi4plants/nfdi4plants_ontology#51]
### Type of Issue

- [ ] Report a Bug
- [ ] Report a Typo or Error
- [ ] Feature Request
- [X] Help or Question

### Comments

Hey, I noticed a small inconsistency in this section of the DPBO: 
```yml
[Term]
id: DPBO:1000086
name: single
def: "placeholder def of single" []
comment: To be transformed to an instance. DB
is_a: DPBO:0000015 ! library layout
property_value: ER_target "GEO_RNASEQ" xsd:string
property_value: ER_target_term "RAW FILES_single or paired-end" xsd:string

[Term]
id: DPBO:1000087
name: paired-end
def: "placeholder def of paired-end" []
comment: To be transformed to an instance. DB
is_a: DPBO:0000015 ! library layout
property_value: ER_target "GEO_RNASEQ" xsd:string
property_value: ER_target_term "RAW FILES_single or paired-end" xsd:string
```
I think `single` should be renamed to `single-end`.
